(function (root) {
  'use strict';
  // { problem: 원문 전체, answer: 빈칸 단어, blankStart: problem 내 answer 시작 인덱스,
  //   meaning: 아이 눈높이 한 줄 뜻풀이 }
  root.proverbs = [
    { problem: '소 잃고 외양간 고친다', answer: '외양간', blankStart: 5,
      meaning: '일이 잘못된 다음에 고치려 하면 이미 늦었다는 뜻이에요.' },
    { problem: '티끌 모아 태산', answer: '티끌', blankStart: 0,
      meaning: '작은 것도 꾸준히 모으면 큰 것이 된다는 뜻이에요.' },
    { problem: '원숭이도 나무에서 떨어진다', answer: '원숭이', blankStart: 0,
      meaning: '아무리 잘하는 사람도 실수할 때가 있다는 뜻이에요.' },
    { problem: '세 살 버릇 여든까지 간다', answer: '버릇', blankStart: 4,
      meaning: '어릴 때 생긴 버릇은 평생 간다는 뜻이에요.' },
    { problem: '등잔 밑이 어둡다', answer: '등잔', blankStart: 0,
      meaning: '가까이 있는 것을 오히려 잘 모를 수 있다는 뜻이에요.' },
    { problem: '우물 안 개구리', answer: '개구리', blankStart: 5,
      meaning: '넓은 세상을 모르고 좁게만 생각한다는 뜻이에요.' },
    { problem: '고양이 목에 방울 달기', answer: '방울', blankStart: 7,
      meaning: '좋은 생각이라도 실제로 하기는 어렵다는 뜻이에요.' },
    { problem: '바늘 도둑이 소 도둑 된다', answer: '바늘', blankStart: 0,
      meaning: '작은 나쁜 짓도 커지면 큰 잘못이 된다는 뜻이에요.' },
    { problem: '열 번 찍어 안 넘어가는 나무 없다', answer: '나무', blankStart: 14,
      meaning: '계속 노력하면 결국 이루어진다는 뜻이에요.' },
    { problem: '낮말은 새가 듣고 밤말은 쥐가 듣는다', answer: '밤말', blankStart: 10,
      meaning: '말은 언제나 조심해야 한다는 뜻이에요.' },
    { problem: '닭 쫓던 개 지붕 쳐다본다', answer: '지붕', blankStart: 7,
      meaning: '애써 하던 일이 실패해 허탈해진다는 뜻이에요.' },
    { problem: '하늘이 무너져도 솟아날 구멍이 있다', answer: '구멍', blankStart: 13,
      meaning: '아무리 힘들어도 길은 있다는 뜻이에요.' },
    { problem: '가재는 게 편', answer: '가재', blankStart: 0,
      meaning: '비슷한 처지에 있는 사람끼리 편을 든다는 뜻이에요.' },
    { problem: '고래 싸움에 새우 등 터진다', answer: '새우', blankStart: 7,
      meaning: '남들 싸움에 애꿎은 사람이 피해를 본다는 뜻이에요.' },
    { problem: '그림의 떡', answer: '그림', blankStart: 0,
      meaning: '아무리 좋아도 가질 수 없으면 소용없다는 뜻이에요.' },
    { problem: '금강산도 식후경', answer: '식후경', blankStart: 5,
      meaning: '아무리 좋은 구경도 배가 불러야 즐겁다는 뜻이에요.' },
    { problem: '까마귀 날자 배 떨어진다', answer: '까마귀', blankStart: 0,
      meaning: '우연히 겹친 일로 억울하게 의심받는다는 뜻이에요.' },
    { problem: '계란으로 바위 치기', answer: '바위', blankStart: 5,
      meaning: '도저히 이길 수 없는 상대에게 덤빈다는 뜻이에요.' },
    { problem: '구슬이 서 말이라도 꿰어야 보배', answer: '구슬', blankStart: 0,
      meaning: '좋은 것도 다듬어야 값어치가 생긴다는 뜻이에요.' },
    { problem: '낫 놓고 기역 자도 모른다', answer: '기역', blankStart: 5,
      meaning: '아주 쉬운 것도 모를 만큼 무식하다는 뜻이에요.' },
    { problem: '믿는 도끼에 발등 찍힌다', answer: '도끼', blankStart: 3,
      meaning: '믿었던 사람에게 오히려 배신당한다는 뜻이에요.' },
    { problem: '발 없는 말이 천리 간다', answer: '천리', blankStart: 8,
      meaning: '소문은 순식간에 멀리 퍼진다는 뜻이에요.' },
    { problem: '배보다 배꼽이 더 크다', answer: '배꼽', blankStart: 4,
      meaning: '중심이 되어야 할 것보다 덧붙은 것이 더 커졌다는 뜻이에요.' },
    { problem: '벼는 익을수록 고개를 숙인다', answer: '고개', blankStart: 8,
      meaning: '훌륭한 사람일수록 겸손하다는 뜻이에요.' },
    { problem: '불난 집에 부채질한다', answer: '부채질', blankStart: 6,
      meaning: '힘든 사람을 더 힘들게 만든다는 뜻이에요.' },
    { problem: '빈 수레가 요란하다', answer: '수레', blankStart: 2,
      meaning: '아는 것 없는 사람이 더 시끄럽게 떠든다는 뜻이에요.' },
    { problem: '사공이 많으면 배가 산으로 간다', answer: '사공', blankStart: 0,
      meaning: '참견하는 사람이 많으면 일이 엉뚱하게 된다는 뜻이에요.' },
    { problem: '서당 개 삼 년이면 풍월을 읊는다', answer: '풍월', blankStart: 11,
      meaning: '오래 보고 들으면 자연히 익히게 된다는 뜻이에요.' },
    { problem: '소문난 잔치에 먹을 것 없다', answer: '잔치', blankStart: 4,
      meaning: '소문이 요란한 것일수록 실속이 없다는 뜻이에요.' },
    { problem: '쇠뿔도 단김에 빼라', answer: '쇠뿔', blankStart: 0,
      meaning: '하려고 마음먹은 일은 바로 해야 한다는 뜻이에요.' },
    { problem: '수박 겉핥기', answer: '겉핥기', blankStart: 3,
      meaning: '속은 모르고 겉만 대충 보고 넘어간다는 뜻이에요.' },
    { problem: '싼 것이 비지떡', answer: '비지떡', blankStart: 5,
      meaning: '싼 물건은 품질도 그만큼 떨어진다는 뜻이에요.' },
    { problem: '아니 땐 굴뚝에 연기 날까', answer: '굴뚝', blankStart: 5,
      meaning: '원인 없이는 결과도 생기지 않는다는 뜻이에요.' },
    { problem: '가는 말이 고와야 오는 말이 곱다', answer: '곱다', blankStart: 16,
      meaning: '내가 잘해야 남도 나에게 잘해 준다는 뜻이에요.' },
    { problem: '우물에서 숭늉 찾는다', answer: '숭늉', blankStart: 5,
      meaning: '너무 성급하게 결과를 바란다는 뜻이에요.' },
    { problem: '울며 겨자 먹기', answer: '겨자', blankStart: 3,
      meaning: '하기 싫어도 어쩔 수 없이 한다는 뜻이에요.' },
    { problem: '원님 덕에 나팔 분다', answer: '나팔', blankStart: 6,
      meaning: '남 덕분에 분에 넘치는 대접을 받는다는 뜻이에요.' },
    { problem: '쥐구멍에도 볕 들 날 있다', answer: '쥐구멍', blankStart: 0,
      meaning: '아무리 힘들어도 좋은 날이 온다는 뜻이에요.' },
    { problem: '지렁이도 밟으면 꿈틀한다', answer: '꿈틀', blankStart: 9,
      meaning: '아무리 순한 사람도 심하게 하면 화를 낸다는 뜻이에요.' },
    { problem: '짚신도 짝이 있다', answer: '짚신', blankStart: 0,
      meaning: '누구에게나 어울리는 짝이 있다는 뜻이에요.' },
    { problem: '참새가 방앗간을 그냥 지나랴', answer: '방앗간', blankStart: 4,
      meaning: '좋아하는 것을 보면 그냥 지나치기 어렵다는 뜻이에요.' },
    { problem: '천 리 길도 한 걸음부터', answer: '걸음', blankStart: 9,
      meaning: '큰 일도 작은 시작에서부터 이루어진다는 뜻이에요.' },
    { problem: '호랑이도 제 말 하면 온다', answer: '호랑이', blankStart: 0,
      meaning: '누군가 이야기를 하면 그 사람이 나타난다는 뜻이에요.' },
    { problem: '호박이 넝쿨째 굴러 들어온다', answer: '넝쿨', blankStart: 4,
      meaning: '뜻밖에 좋은 일이 한꺼번에 생긴다는 뜻이에요.' },
    { problem: '가는 날이 장날', answer: '장날', blankStart: 6,
      meaning: '어떤 일을 하려는 날에 우연히 다른 일이 겹친다는 뜻이에요.' },
    { problem: '갈수록 태산', answer: '태산', blankStart: 4,
      meaning: '갈수록 더 힘든 일이 생긴다는 뜻이에요.' },
    { problem: '개구리 올챙이 적 생각 못 한다', answer: '올챙이', blankStart: 4,
      meaning: '형편이 나아지면 예전 어려움을 잊는다는 뜻이에요.' },
    { problem: '개똥도 약에 쓰려면 없다', answer: '개똥', blankStart: 0,
      meaning: '흔하던 것도 막상 필요하면 찾기 어렵다는 뜻이에요.' },
    { problem: '고생 끝에 낙이 온다', answer: '고생', blankStart: 0,
      meaning: '힘든 일을 견디면 좋은 날이 온다는 뜻이에요.' },
    { problem: '백지장도 맞들면 낫다', answer: '맞들면', blankStart: 5,
      meaning: '아무리 쉬운 일도 함께하면 더 쉬워진다는 뜻이에요.' },
    { problem: '공자 앞에서 문자 쓴다', answer: '문자', blankStart: 7,
      meaning: '잘 아는 사람 앞에서 아는 척을 한다는 뜻이에요.' },
    { problem: '귀에 걸면 귀걸이 코에 걸면 코걸이', answer: '코걸이', blankStart: 16,
      meaning: '기준이 분명하지 않아 이렇게도 저렇게도 해석된다는 뜻이에요.' },
    { problem: '꼬리가 길면 밟힌다', answer: '꼬리', blankStart: 0,
      meaning: '나쁜 짓을 자꾸 하면 결국 들킨다는 뜻이에요.' },
    { problem: '꿈보다 해몽이 좋다', answer: '해몽', blankStart: 4,
      meaning: '별것 아닌 일을 좋게 풀이해 받아들인다는 뜻이에요.' },
    { problem: '달면 삼키고 쓰면 뱉는다', answer: '뱉는다', blankStart: 10,
      meaning: '자기에게 이로우면 좋아하고 아니면 버린다는 뜻이에요.' },
    { problem: '돌다리도 두들겨 보고 건너라', answer: '두들겨', blankStart: 5,
      meaning: '잘 아는 일도 다시 한번 꼼꼼히 확인하라는 뜻이에요.' },
    { problem: '도둑이 제 발 저리다', answer: '도둑', blankStart: 0,
      meaning: '잘못한 사람이 스스로 불안해한다는 뜻이에요.' },
    { problem: '말 한마디에 천 냥 빚을 갚는다', answer: '한마디', blankStart: 2,
      meaning: '말을 잘하면 큰 문제도 해결할 수 있다는 뜻이에요.' },
    { problem: '목마른 사람이 우물 판다', answer: '우물', blankStart: 8,
      meaning: '꼭 필요한 사람이 먼저 나서서 해결한다는 뜻이에요.' },
    { problem: '못된 송아지 엉덩이에 뿔 난다', answer: '송아지', blankStart: 3,
      meaning: '모자란 사람이 더 못된 짓을 한다는 뜻이에요.' },
    { problem: '무소식이 희소식', answer: '희소식', blankStart: 5,
      meaning: '소식이 없는 것도 잘 지낸다는 좋은 신호라는 뜻이에요.' },
    { problem: '뱁새가 황새 따라가면 다리가 찢어진다', answer: '황새', blankStart: 4,
      meaning: '자기 힘에 안 맞게 남을 따라 하면 힘들어진다는 뜻이에요.' },
    { problem: '뿌린 대로 거둔다', answer: '거둔다', blankStart: 6,
      meaning: '자기가 한 대로 결과를 돌려받는다는 뜻이에요.' },
    { problem: '서울에서 김 서방 찾기', answer: '서울', blankStart: 0,
      meaning: '정보도 없이 막연히 찾으려 한다는 뜻이에요.' },
    { problem: '손바닥으로 하늘 가리기', answer: '손바닥', blankStart: 0,
      meaning: '뻔히 드러난 일을 억지로 숨기려 한다는 뜻이에요.' },
    { problem: '십 년이면 강산도 변한다', answer: '강산', blankStart: 6,
      meaning: '세월이 지나면 모든 것이 많이 바뀐다는 뜻이에요.' },
    { problem: '아닌 밤중에 홍두깨', answer: '홍두깨', blankStart: 7,
      meaning: '갑작스럽고 엉뚱한 일이 벌어진다는 뜻이에요.' },
    { problem: '언 발에 오줌 누기', answer: '오줌', blankStart: 5,
      meaning: '잠깐은 도움이 돼도 금방 더 나빠지는 방법이라는 뜻이에요.' },
    { problem: '옷이 날개다', answer: '날개', blankStart: 3,
      meaning: '좋은 옷을 입으면 사람이 더 돋보인다는 뜻이에요.' },
    { problem: '자라 보고 놀란 가슴 솥뚜껑 보고 놀란다', answer: '솥뚜껑', blankStart: 12,
      meaning: '한 번 놀란 일 때문에 비슷한 것만 봐도 겁낸다는 뜻이에요.' },
    { problem: '작은 고추가 더 맵다', answer: '맵다', blankStart: 9,
      meaning: '몸집이 작아도 능력이나 야무짐은 더 뛰어나다는 뜻이에요.' },
    { problem: '지성이면 감천', answer: '감천', blankStart: 5,
      meaning: '정성을 다하면 결국 하늘도 감동해 돕는다는 뜻이에요.' },
    { problem: '찬물도 위아래가 있다', answer: '찬물', blankStart: 0,
      meaning: '무슨 일이든 순서와 차례를 지켜야 한다는 뜻이에요.' },
    { problem: '첫술에 배부르랴', answer: '첫술', blankStart: 0,
      meaning: '처음부터 큰 성과를 바랄 수는 없다는 뜻이에요.' },
    { problem: '콩으로 메주를 쑨다 해도 곧이듣지 않는다', answer: '메주', blankStart: 4,
      meaning: '아무리 사실을 말해도 믿어 주지 않는다는 뜻이에요.' },
    { problem: '핑계 없는 무덤 없다', answer: '무덤', blankStart: 6,
      meaning: '누구나 잘못에는 변명할 거리를 만든다는 뜻이에요.' },
    { problem: '하나를 보면 열을 안다', answer: '하나', blankStart: 0,
      meaning: '작은 행동 하나로 그 사람 전체를 짐작할 수 있다는 뜻이에요.' },
    { problem: '호미로 막을 것을 가래로 막는다', answer: '가래', blankStart: 10,
      meaning: '작을 때 처리하지 않아 더 큰 힘이 든다는 뜻이에요.' },
    { problem: '황소 뒷걸음치다 쥐 잡는다', answer: '황소', blankStart: 0,
      meaning: '어쩌다 한 일이 우연히 잘 맞아떨어진다는 뜻이에요.' },
    { problem: '가랑비에 옷 젖는 줄 모른다', answer: '가랑비', blankStart: 0,
      meaning: '작은 일도 계속되면 어느새 큰 영향을 준다는 뜻이에요.' },
    { problem: '강 건너 불구경', answer: '불구경', blankStart: 5,
      meaning: '자기와 상관없다는 듯 남의 일을 구경만 한다는 뜻이에요.' },
    { problem: '개천에서 용 난다', answer: '개천', blankStart: 0,
      meaning: '어려운 환경에서도 훌륭한 사람이 나올 수 있다는 뜻이에요.' },
    { problem: '누워서 떡 먹기', answer: '누워서', blankStart: 0,
      meaning: '아주 쉽게 할 수 있는 일이라는 뜻이에요.' },
    { problem: '하늘의 별 따기', answer: '하늘', blankStart: 0,
      meaning: '이루기 너무 어려운 일이라는 뜻이에요.' },
    { problem: '떡 본 김에 제사 지낸다', answer: '제사', blankStart: 7,
      meaning: '좋은 기회가 온 김에 하려던 일을 함께 해치운다는 뜻이에요.' },
    { problem: '번갯불에 콩 볶아 먹는다', answer: '번갯불', blankStart: 0,
      meaning: '일을 아주 빠르게 해치운다는 뜻이에요.' },
    { problem: '부뚜막의 소금도 집어넣어야 짜다', answer: '소금', blankStart: 5,
      meaning: '좋은 재료도 쓰지 않으면 소용없다는 뜻이에요.' },
    { problem: '빛 좋은 개살구', answer: '개살구', blankStart: 5,
      meaning: '겉보기는 좋지만 속은 별로라는 뜻이에요.' },
    { problem: '제 눈에 안경', answer: '안경', blankStart: 5,
      meaning: '남이 보기엔 별로여도 자기 눈엔 예뻐 보인다는 뜻이에요.' },
    { problem: '될성부른 나무는 떡잎부터 알아본다', answer: '떡잎', blankStart: 9,
      meaning: '크게 될 사람은 어릴 때부터 남다르다는 뜻이에요.' },
    { problem: '무쇠도 갈면 바늘 된다', answer: '무쇠', blankStart: 0,
      meaning: '꾸준히 노력하면 무엇이든 이룰 수 있다는 뜻이에요.' },
    { problem: '사촌이 땅을 사면 배가 아프다', answer: '사촌', blankStart: 0,
      meaning: '남이 잘되는 것을 괜히 배 아파한다는 뜻이에요.' },
    { problem: '시작이 반이다', answer: '시작', blankStart: 0,
      meaning: '무슨 일이든 시작하면 이미 절반은 한 셈이라는 뜻이에요.' },
    { problem: '열 손가락 깨물어 안 아픈 손가락 없다', answer: '손가락', blankStart: 2,
      meaning: '자식은 누구나 다 똑같이 소중하다는 뜻이에요.' },
    { problem: '윗물이 맑아야 아랫물이 맑다', answer: '아랫물', blankStart: 8,
      meaning: '윗사람이 바르게 행동해야 아랫사람도 따라 한다는 뜻이에요.' },
    { problem: '형만 한 아우 없다', answer: '아우', blankStart: 5,
      meaning: '동생이 아무리 잘해도 형만큼 못 미친다는 뜻이에요.' },
    { problem: '황금 보기를 돌같이 하라', answer: '황금', blankStart: 0,
      meaning: '재물에 욕심내지 말고 바르게 살라는 뜻이에요.' },
    { problem: '가지 많은 나무에 바람 잘 날 없다', answer: '바람', blankStart: 10,
      meaning: '자식이 많으면 부모 걱정이 끊이지 않는다는 뜻이에요.' },
    { problem: '구르는 돌은 이끼가 안 낀다', answer: '이끼', blankStart: 7,
      meaning: '부지런히 노력하는 사람은 계속 발전한다는 뜻이에요.' },
    { problem: '도토리 키 재기', answer: '도토리', blankStart: 0,
      meaning: '비슷비슷한 것끼리 견주어 봐야 별 차이 없다는 뜻이에요.' },
  ];
  root.STAGE_COUNT = root.proverbs.length; // 총 스테이지 수의 단일 소스
})(globalThis.Sokdam = globalThis.Sokdam || {});
